version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
    restart: always

  redis:
    image: redis
    ports:
      - 6380:6379
    restart: always

  app:
    build: .
    ports:
      - 8081:8080
    depends_on:
      - mysql
      - redis
    restart: always